spring:
  thymeleaf:
    cache: false

  redis:
    host: 192.168.170.135
    port: 6379
    database: 0
    connect-timeout: 10000ms
  #    超时时间
    lettuce:
      pool:
#        最大连接数量 默认是8
        max-active: 8
#        最大连接阻塞时间 默认-1
        max-wait: 10000ms
        max-idle: 200
        min-idle: 5

  rabbitmq:
    host: 192.168.170.135
    username: guest
    password: guest
    virtual-host: /
    port: 5672
    listener:
      simple:
        concurrency: 10
        max-concurrency: 10
        prefetch: 1
#        启动时默认启动容器
        auto-startup: true
#        拒绝时默认重新入队
        default-requeue-rejected: true
    template:
      retry:
        enabled: true
        initial-interval: 1000ms
        max-attempts: 3
        max-interval: 10000ms
        multiplier: 1


  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seckill?useUnicode=true&characterEncoding=utf-8&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=GMT%2B8
    username: chh
    password: 123
    hikari:
      pool-name: DataHikariCP
      minimum-idle: 5
      #      最大存活时间 默认十分钟
      idle-timeout: 180000
      maximum-pool-size: 10
      auto-commit: true
      #      默认半小时
      max-lifetime: 180000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  web:
    resources:
      chain:
        compressed: true
        cache: true
        enabled: true
        html-application-cache: true
      add-mappings: true
      cache:
        cachecontrol:
          max-age: 3600
      static-locations: classpath:/static/

mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
  type-aliases-package: com.example.seckill.pojo
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# Mybatis SQL打印 方法接口所在的包
logging:
  level:
    com.example.seckilldemo.mapper: debug
